database:
  type: "postgres"
  postgresql:
    host: "localhost"
    port: 5432
    database: "trading_bot_db"
    user: "postgres"
    password: ".."
  sqlite:
    path: "trading_bot.db"
trading:
  symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT"]
